apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: crypto-cluster
  namespace: kafka
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          # Entrada inicial (Mapa do Cluster)
          bootstrap:
            host: 127.0.0.1
          # Onde os dados realmente estão (Sobrescrita)
          brokers:
            - broker: 0
              advertisedHost: 127.0.0.1
              advertisedPort: 9095  # <--- O PULO DO GATO: Força o cliente a usar o segundo túnel
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}